### ISSUE TITLE
LICENSE contains wrong license text

### ISSUE THREAD

**Issue by fschlich** [paultcochrane/Math-Base85#2]
The LICENSE file you added contains language for Artistic 2.0, while README and Base85.pm say "same license terms as Perl itself", which is Artistic 1 or GPL 1+ (see https://dev.perl.org/licenses/ and/or 'perldoc perlartistic' / ' perldoc perlgpl')

Could you update LICENSE accordingly?

**Comment by paultcochrane** [comment]
Thanks for pointing that out!  Fixed in de649d5.
